import fs from "fs";
import path from "path";

const root = process.cwd();

const sourceFiles = {
  recommendations: "data/matchdayRecommendations_fantasyPool_v3.json",
  projections: "data/playerMatchdayProjections_fantasyPool_v3.json",
  financeMetrics: "data/playerFinanceMetrics_fantasyPool_v1.json",
  scorePredictions: "data/scorePredictions_fantasyPool_v3.json",
  readinessQa: "data/publicPreviewPromotionReadinessQa_v1.json",
  officialPlayers: "data/officialFantasyPlayers_v0.json",
  officialRules: "data/officialFantasyRules_v0.json",
  officialSquads: "data/officialSquads_v0.json",
  readiness: "data/officialDataReadiness_v0.json"
};

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
}

function arrayFromFirstRecord(record, keys) {
  for (const key of keys) {
    if (Array.isArray(record?.[key])) {
      return record[key];
    }
  }

  return [];
}

function writeBrowserData(relativePath, assignments, sourcePaths) {
  const header = [
    "// Generated by scripts/buildFantasyPoolPreviewBrowserData.mjs.",
    `// Source files: ${sourcePaths.join(", ")}`,
    "// Official Fantasy Pool Preview only. Not final-squad-backed.",
    ""
  ].join("\n");

  const body = Object.entries(assignments)
    .map(([globalName, value]) => `window.${globalName} = ${JSON.stringify(value)};`)
    .join("\n\n");

  fs.writeFileSync(path.join(root, relativePath), `${header}${body}\n`);
}

const recommendations = readJson(sourceFiles.recommendations);
const projections = readJson(sourceFiles.projections);
const financeMetrics = readJson(sourceFiles.financeMetrics);
const scorePredictions = readJson(sourceFiles.scorePredictions);
const readinessQa = readJson(sourceFiles.readinessQa);
const officialPlayers = readJson(sourceFiles.officialPlayers);
const officialRules = readJson(sourceFiles.officialRules);
const officialSquads = readJson(sourceFiles.officialSquads);
const readiness = readJson(sourceFiles.readiness);

const recommendationCandidates = arrayFromFirstRecord(recommendations, ["recommendationCandidates"]);
const playerMatchdayProjections = arrayFromFirstRecord(projections, ["playerMatchdayProjections"]);
const playerFinanceMetrics = arrayFromFirstRecord(financeMetrics, ["playerFinanceMetrics"]);
const fixtureScorePredictions = arrayFromFirstRecord(scorePredictions, ["fixtureScorePredictions"]);
const teamFixturePredictions = arrayFromFirstRecord(scorePredictions, ["teamFixturePredictions"]);
const officialFantasyPlayers = arrayFromFirstRecord(officialPlayers, [
  "players",
  "officialFantasyPlayers",
  "official_fantasy_players"
]);
const squadRows = arrayFromFirstRecord(officialSquads, ["squads", "officialSquads", "players"]);

const publicWarningCopy = [
  "Uses official fantasy prices, positions, and scoring.",
  "Final squad status is not yet source-backed.",
  "Recommendations may change after final squad confirmation.",
  "Rules still have manual-review warnings.",
  "Team Builder remains prototype/blocked until final squad and rule gates pass."
];

const officialDataStatus = {
  schema_version: "fantasy_pool_official_data_status_browser_v1",
  generated_at: new Date().toISOString(),
  source_checked: readinessQa.source_checked || recommendations.source_checked || "2026-06-02",
  model_stage: "official_fantasy_pool_preview",
  public_label: "Official Fantasy Pool Preview",
  readiness_status: readiness.status || readiness.readiness_status || "blocked_waiting_for_official_fantasy_data",
  readiness_verdict: readinessQa.verdict || "ready_for_public_preview_with_warnings",
  safe_for_public_preview_with_warnings: Boolean(readinessQa.safe_for_public_preview_with_warnings),
  safe_for_final_public_recommendations: false,
  safe_for_team_builder_promotion: false,
  team_builder_status: "prototype_blocked",
  final_squad_source_status: "not_source_backed",
  rules_status: officialRules.status || officialRules.import_status || "official_imported_needs_manual_review",
  browser_ready_preview_files: [
    "fantasyPoolRecommendationsData.js",
    "fantasyPoolMatchdayProjectionsData.js",
    "fantasyPoolFinanceMetricsData.js",
    "fantasyPoolScorePredictionsData.js",
    "fantasyPoolOfficialDataStatusData.js"
  ],
  active_legacy_files_preserved: [
    "matchdayRecommendationsData.js",
    "matchdayProjectionsData.js",
    "scorePredictionsData.js",
    "financePlayersData.js",
    "playersData.js"
  ],
  warning_copy: publicWarningCopy,
  public_warning_html: "Official Fantasy Pool Preview. These picks use official fantasy prices, positions, and scoring. Final squad status is not yet source-backed, so recommendations may change.",
  team_builder_warning_html: "Team Builder is still in prototype mode. Official prices and rules are available, but final squad status is not source-backed yet. Do not treat generated squads as final.",
  status_points: [
    { label: "Official fantasy pool", status: "imported" },
    { label: "Official prices", status: "imported" },
    { label: "Official positions", status: "imported" },
    { label: "Official scoring", status: "imported_with_manual_review_warnings" },
    { label: "Final squads", status: "not_source_backed" },
    { label: "Mystery Booster", status: "unknown" },
    { label: "Deadline semantics", status: "under_review" },
    { label: "Recommendations", status: "preview_not_final" },
    { label: "Team Builder", status: "prototype_blocked" }
  ],
  summary: {
    recommendation_candidates: recommendationCandidates.length,
    player_matchday_projection_rows: playerMatchdayProjections.length,
    finance_metric_players: playerFinanceMetrics.length,
    fixture_score_predictions: fixtureScorePredictions.length,
    team_fixture_predictions: teamFixturePredictions.length,
    official_fantasy_players: officialFantasyPlayers.length || officialPlayers.summary?.total_players || 1481,
    official_squad_rows: squadRows.length || officialSquads.summary?.total_rows || 1481,
    confirmed_final_squad_rows: officialSquads.summary?.confirmed_final_squad_rows || officialSquads.summary?.confirmed_final_squad || 0,
    fantasy_pool_only_rows: officialSquads.summary?.fantasy_selectable_only_rows || officialSquads.summary?.selectable_fantasy_player || 1256,
    squad_review_rows: officialSquads.summary?.review_rows || 225
  },
  source_files: sourceFiles,
  stop_conditions_before_final_promotion: [
    "Final squads are not source-backed.",
    "Official rules still have manual-review warnings for Mystery Booster and deadline semantics.",
    "Team Builder remains prototype/blocked.",
    "Preview browser-ready files must remain labeled as Official Fantasy Pool Preview."
  ]
};

writeBrowserData(
  "fantasyPoolRecommendationsData.js",
  {
    FANTASY_POOL_RECOMMENDATIONS_DATA: recommendations,
    FANTASY_POOL_RECOMMENDATION_CANDIDATES: recommendationCandidates,
    FANTASY_POOL_RECOMMENDATIONS_SUMMARY: recommendations.summary || null
  },
  [sourceFiles.recommendations]
);

writeBrowserData(
  "fantasyPoolMatchdayProjectionsData.js",
  {
    FANTASY_POOL_MATCHDAY_PROJECTIONS_DATA: projections,
    FANTASY_POOL_PLAYER_MATCHDAY_PROJECTIONS: playerMatchdayProjections,
    FANTASY_POOL_MATCHDAY_PROJECTIONS_SUMMARY: projections.summary || null
  },
  [sourceFiles.projections]
);

writeBrowserData(
  "fantasyPoolFinanceMetricsData.js",
  {
    FANTASY_POOL_FINANCE_METRICS_DATA: financeMetrics,
    FANTASY_POOL_PLAYER_FINANCE_METRICS: playerFinanceMetrics,
    FANTASY_POOL_FINANCE_METRICS_SUMMARY: financeMetrics.summary || null
  },
  [sourceFiles.financeMetrics]
);

writeBrowserData(
  "fantasyPoolScorePredictionsData.js",
  {
    FANTASY_POOL_SCORE_PREDICTIONS_DATA: scorePredictions,
    FANTASY_POOL_SCORE_FIXTURE_PREDICTIONS: fixtureScorePredictions,
    FANTASY_POOL_TEAM_FIXTURE_PREDICTIONS: teamFixturePredictions,
    FANTASY_POOL_SCORE_PREDICTIONS_SUMMARY: scorePredictions.summary || null
  },
  [sourceFiles.scorePredictions]
);

writeBrowserData(
  "fantasyPoolOfficialDataStatusData.js",
  {
    FANTASY_POOL_OFFICIAL_DATA_STATUS: officialDataStatus
  },
  [
    sourceFiles.readinessQa,
    sourceFiles.officialPlayers,
    sourceFiles.officialRules,
    sourceFiles.officialSquads,
    sourceFiles.readiness
  ]
);

console.log("Generated Official Fantasy Pool Preview browser data files.");
