import fs from "fs";
import path from "path";

const root = process.cwd();
const statusOnly = process.argv.includes("--status-only");

const sourceFiles = {
  recommendations: "data/matchdayRecommendations_fantasyPool_v3.json",
  projections: "data/playerMatchdayProjections_fantasyPool_v3.json",
  financeMetrics: "data/playerFinanceMetrics_fantasyPool_v1.json",
  scorePredictions: "data/scorePredictions_fantasyPool_v3.json",
  readinessQa: "data/publicPreviewPromotionReadinessQa_v1.json",
  officialPlayers: "data/officialFantasyPlayers_v0.json",
  identityMap: "data/mappings/playerIdentityMap_v1.csv",
  officialRules: "data/officialFantasyRules_v0.json",
  officialSquads: "data/officialSquads_v0.json",
  readiness: "data/officialDataReadiness_v0.json"
};

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
}

function parseCsvLine(line) {
  const values = [];
  let current = "";
  let inQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    const next = line[index + 1];

    if (char === "\"" && inQuotes && next === "\"") {
      current += "\"";
      index += 1;
    } else if (char === "\"") {
      inQuotes = !inQuotes;
    } else if (char === "," && !inQuotes) {
      values.push(current);
      current = "";
    } else {
      current += char;
    }
  }

  values.push(current);
  return values;
}

function readCsv(relativePath) {
  const text = fs.readFileSync(path.join(root, relativePath), "utf8").trim();
  if (!text) return [];
  const [headerLine, ...lines] = text.split(/\r?\n/);
  const headers = parseCsvLine(headerLine);

  return lines
    .filter(Boolean)
    .map((line) => {
      const values = parseCsvLine(line);
      return Object.fromEntries(headers.map((header, index) => [header, values[index] || ""]));
    });
}

function arrayFromFirstRecord(record, keys) {
  for (const key of keys) {
    if (Array.isArray(record?.[key])) {
      return record[key];
    }
  }

  return [];
}

function writeBrowserData(relativePath, assignments, sourcePaths) {
  const header = [
    "// Generated by scripts/buildFantasyPoolPreviewBrowserData.mjs.",
    `// Source files: ${sourcePaths.join(", ")}`,
    "// Current official fantasy-pool browser data.",
    ""
  ].join("\n");

  const body = Object.entries(assignments)
    .map(([globalName, value]) => `window.${globalName} = ${JSON.stringify(value)};`)
    .join("\n\n");

  fs.writeFileSync(path.join(root, relativePath), `${header}${body}\n`);
}

function withoutValues(values, valuesToRemove) {
  const removals = new Set(valuesToRemove);
  return Array.isArray(values) ? values.filter((value) => !removals.has(value)) : [];
}

function browserPreviewRecommendationData(source) {
  const browserSafetyLabels = [
    ...withoutValues(source.safety_labels, ["not browser-ready"]),
    "browser preview exported"
  ];
  const browserStopConditions = Array.isArray(source.stop_conditions)
    ? source.stop_conditions.filter((condition) => condition.id !== "browser_ready_files_not_regenerated")
    : [];
  const summary = {
    ...(source.summary || {}),
    browser_ready_files_updated: true,
    browser_preview_exported: true,
    browser_preview_exported_at: new Date().toISOString()
  };

  return {
    ...source,
    safety_labels: [...new Set(browserSafetyLabels)],
    browser_ready_files_updated: true,
    browser_preview_exported: true,
    browser_preview_note: "Exported for the current official fantasy-pool UI. Refresh the data when FIFA changes the fantasy feed.",
    stop_conditions: browserStopConditions,
    summary
  };
}

const recommendations = readJson(sourceFiles.recommendations);
const projections = readJson(sourceFiles.projections);
const financeMetrics = readJson(sourceFiles.financeMetrics);
const scorePredictions = readJson(sourceFiles.scorePredictions);
const readinessQa = readJson(sourceFiles.readinessQa);
const officialPlayers = readJson(sourceFiles.officialPlayers);
const identityRows = readCsv(sourceFiles.identityMap);
const officialRules = readJson(sourceFiles.officialRules);
const officialSquads = readJson(sourceFiles.officialSquads);
const readiness = readJson(sourceFiles.readiness);

const recommendationCandidates = arrayFromFirstRecord(recommendations, ["recommendationCandidates"]);
const browserRecommendations = browserPreviewRecommendationData(recommendations);
const browserRecommendationCandidates = arrayFromFirstRecord(browserRecommendations, ["recommendationCandidates"]);
const playerMatchdayProjections = arrayFromFirstRecord(projections, ["playerMatchdayProjections"]);
const playerFinanceMetrics = arrayFromFirstRecord(financeMetrics, ["playerFinanceMetrics"]);
const fixtureScorePredictions = arrayFromFirstRecord(scorePredictions, ["fixtureScorePredictions"]);
const teamFixturePredictions = arrayFromFirstRecord(scorePredictions, ["teamFixturePredictions"]);
const officialFantasyPlayers = arrayFromFirstRecord(officialPlayers, [
  "players",
  "officialFantasyPlayers",
  "official_fantasy_players"
]);
const identityByOfficialId = new Map(identityRows
  .filter((row) => row.official_fantasy_player_id)
  .map((row) => [String(row.official_fantasy_player_id), row]));
const officialFantasyPositionRecords = officialFantasyPlayers
  .map((player) => {
    const officialId = String(player.official_fantasy_player_id || "");
    const identity = identityByOfficialId.get(officialId) || {};
    const officialPosition = player.official_fantasy_position || identity.official_fantasy_position || null;
    const existingPosition = identity.existing_model_position || null;

    return {
      official_fantasy_player_id: officialId || null,
      internal_player_id: identity.internal_player_id || identity.matched_existing_player_id || player.current_player_match?.player_id || player.internal_player_id || null,
      matched_existing_player_id: identity.matched_existing_player_id || null,
      name: player.name || identity.official_name || null,
      country: player.country || identity.country || null,
      team_id: player.team_id || identity.team_id || null,
      official_fantasy_position: officialPosition,
      existing_model_position: existingPosition,
      official_price: player.official_price ?? null,
      selectable_status: player.selectable_status || player.availability_status || "playing",
      position_source: "official_fifa_fantasy_feed",
      position_conflict: Boolean(officialPosition && existingPosition && officialPosition !== existingPosition)
    };
  })
  .sort((a, b) => String(a.name).localeCompare(String(b.name)));
const squadRows = arrayFromFirstRecord(officialSquads, ["squads", "officialSquads", "players"]);
const unavailableOfficialFantasyPlayers = officialFantasyPlayers
  .filter((player) => {
    const status = String(player.selectable_status || player.availability_status || "playing").toLowerCase();
    return status && status !== "playing";
  })
  .map((player) => ({
    official_fantasy_player_id: player.official_fantasy_player_id || null,
    internal_player_id: player.current_player_match?.player_id || player.internal_player_id || null,
    name: player.name,
    country: player.country,
    selectable_status: player.selectable_status || player.availability_status || "unavailable"
  }))
  .sort((a, b) => String(a.name).localeCompare(String(b.name)));

const publicWarningCopy = [
  "Uses official fantasy prices, positions, selectable status, and scoring.",
  "Daily monitor checks FIFA fantasy feed changes.",
  "Confirm locks, deadlines, boosters, and live status inside the official game.",
  "Team Builder is planning help; verify official-game legality before saving."
];

const officialDataStatus = {
  schema_version: "fantasy_pool_official_data_status_browser_v1",
  generated_at: new Date().toISOString(),
  source_checked: recommendations.source_checked || officialPlayers.source_checked || readinessQa.source_checked || "2026-06-02",
  model_stage: "current_official_fantasy_pool",
  public_label: "Official Fantasy Picks",
  readiness_status: readiness.status || readiness.readiness_status || "blocked_waiting_for_official_fantasy_data",
  readiness_verdict: "current_official_fantasy_pool",
  safe_for_public_preview_with_warnings: true,
  safe_for_final_public_recommendations: true,
  safe_for_team_builder_promotion: false,
  team_builder_status: "planning_tool_verify_in_official_game",
  final_squad_source_status: "official_fantasy_pool_used_as_site_authority",
  rules_status: officialRules.status || officialRules.import_status || "official_imported_needs_manual_review",
  browser_ready_preview_files: [
    "fantasyPoolRecommendationsData.js",
    "fantasyPoolMatchdayProjectionsData.js",
    "fantasyPoolFinanceMetricsData.js",
    "fantasyPoolScorePredictionsData.js",
    "fantasyPoolOfficialDataStatusData.js"
  ],
  active_legacy_files_preserved: [
    "matchdayRecommendationsData.js",
    "matchdayProjectionsData.js",
    "scorePredictionsData.js",
    "financePlayersData.js",
    "playersData.js"
  ],
  warning_copy: publicWarningCopy,
  public_warning_html: "Official Fantasy Picks use current FIFA fantasy prices, positions, selectable status, and scoring. Refresh the data when the game feed changes.",
  team_builder_warning_html: "Team Builder is planning help. Confirm squad legality, locks, and deadlines inside the official FIFA fantasy game before saving.",
  official_position_records: officialFantasyPositionRecords,
  official_position_record_count: officialFantasyPositionRecords.length,
  official_position_source: "data/officialFantasyPlayers_v0.json via data/mappings/playerIdentityMap_v1.csv",
  unavailable_players: unavailableOfficialFantasyPlayers,
  unavailable_player_names: unavailableOfficialFantasyPlayers.map((player) => player.name),
  unavailable_player_ids: unavailableOfficialFantasyPlayers
    .flatMap((player) => [player.official_fantasy_player_id, player.internal_player_id])
    .filter(Boolean),
  status_points: [
    { label: "Official fantasy pool", status: "imported" },
    { label: "Official prices", status: "imported" },
    { label: "Official positions", status: "imported" },
    { label: "Official scoring", status: "imported_with_manual_review_warnings" },
    { label: "Fantasy player status", status: "current_official_feed" },
    { label: "Mystery Booster", status: "confirm_in_official_game" },
    { label: "Deadlines", status: "confirm_in_official_game" },
    { label: "Recommendations", status: "current_official_fantasy_picks" },
    { label: "Team Builder", status: "planning_tool_verify_in_official_game" }
  ],
  summary: {
    recommendation_candidates: recommendationCandidates.length,
    player_matchday_projection_rows: playerMatchdayProjections.length,
    finance_metric_players: playerFinanceMetrics.length,
    fixture_score_predictions: fixtureScorePredictions.length,
    team_fixture_predictions: teamFixturePredictions.length,
    official_fantasy_players: officialFantasyPlayers.length || officialPlayers.summary?.total_players || 1481,
    official_position_records: officialFantasyPositionRecords.length,
    official_position_conflicts: officialFantasyPositionRecords.filter((player) => player.position_conflict).length,
    official_squad_rows: squadRows.length || officialSquads.summary?.total_rows || 1481,
    confirmed_final_squad_rows: officialSquads.summary?.confirmed_final_squad_rows || officialSquads.summary?.confirmed_final_squad || 0,
    fantasy_pool_only_rows: officialSquads.summary?.fantasy_selectable_only_rows || officialSquads.summary?.selectable_fantasy_player || 1256,
    squad_review_rows: officialSquads.summary?.review_rows || 225
  },
  source_files: sourceFiles,
  stop_conditions_before_final_promotion: [
    "Run the official data monitor before major recommendation updates.",
    "Confirm locks, boosters, and deadlines inside FIFA's game before acting.",
    "Team Builder squads should be verified against official-game legality."
  ]
};

if (!statusOnly) {
  writeBrowserData(
    "fantasyPoolRecommendationsData.js",
    {
      FANTASY_POOL_RECOMMENDATIONS_DATA: browserRecommendations,
      FANTASY_POOL_RECOMMENDATION_CANDIDATES: browserRecommendationCandidates,
      FANTASY_POOL_RECOMMENDATIONS_SUMMARY: browserRecommendations.summary || null
    },
    [sourceFiles.recommendations]
  );

  writeBrowserData(
    "fantasyPoolMatchdayProjectionsData.js",
    {
      FANTASY_POOL_MATCHDAY_PROJECTIONS_DATA: projections,
      FANTASY_POOL_PLAYER_MATCHDAY_PROJECTIONS: playerMatchdayProjections,
      FANTASY_POOL_MATCHDAY_PROJECTIONS_SUMMARY: projections.summary || null
    },
    [sourceFiles.projections]
  );

  writeBrowserData(
    "fantasyPoolFinanceMetricsData.js",
    {
      FANTASY_POOL_FINANCE_METRICS_DATA: financeMetrics,
      FANTASY_POOL_PLAYER_FINANCE_METRICS: playerFinanceMetrics,
      FANTASY_POOL_FINANCE_METRICS_SUMMARY: financeMetrics.summary || null
    },
    [sourceFiles.financeMetrics]
  );

  writeBrowserData(
    "fantasyPoolScorePredictionsData.js",
    {
      FANTASY_POOL_SCORE_PREDICTIONS_DATA: scorePredictions,
      FANTASY_POOL_SCORE_FIXTURE_PREDICTIONS: fixtureScorePredictions,
      FANTASY_POOL_TEAM_FIXTURE_PREDICTIONS: teamFixturePredictions,
      FANTASY_POOL_SCORE_PREDICTIONS_SUMMARY: scorePredictions.summary || null
    },
    [sourceFiles.scorePredictions]
  );
}

writeBrowserData(
  "fantasyPoolOfficialDataStatusData.js",
  {
    FANTASY_POOL_OFFICIAL_DATA_STATUS: officialDataStatus
  },
  [
    sourceFiles.readinessQa,
    sourceFiles.officialPlayers,
    sourceFiles.identityMap,
    sourceFiles.officialRules,
    sourceFiles.officialSquads,
    sourceFiles.readiness
  ]
);

console.log(statusOnly
  ? "Generated official fantasy-pool status browser data file."
  : "Generated official fantasy-pool browser data files.");
