import { readFile, writeFile } from "node:fs/promises";

const INPUT = "data/officialFantasyRules_v0.json";
const ROOT_RULES = "fantasyRules.json";
const DATA_RULES = "data/fantasyRules.json";
const BROWSER_RULES = "fantasyRulesData.js";

function snakeRules(rules) {
  return {
    rules_version: rules.rulesVersion,
    rules_status: "official_imported_with_deadline_manual_check",
    public_status: "Official FIFA fantasy rules imported for squad structure, budget, positions, country limits, scoring, transfers, and boosters. Confirm live deadlines, locks, and played/unplayed state inside FIFA before acting.",
    source_checked: rules.sourceChecked,
    source_ids: rules.sourceIds || [],
    squad: {
      total_players: rules.squad.totalPlayers,
      positions: rules.squad.positions
    },
    starting_lineup: {
      total_players: rules.startingLineup.totalPlayers,
      allowed_formations: rules.startingLineup.allowedFormations
    },
    budget: {
      initial_budget: rules.budget.initialBudget,
      knockout_increase: rules.budget.knockoutIncrease,
      currency_label: rules.budget.currencyLabel || "$m",
      price_change_rules: rules.budget.priceChangeRules || null,
      knockout_increase_timing: rules.budget.knockoutIncreaseTiming || null
    },
    country_limits: {
      group_stage_max_per_country: rules.countryLimits.groupStageMaxPerCountry,
      knockout_limits: rules.countryLimits.knockoutLimits || {}
    },
    captain: {
      captain_required: rules.captain.captainRequired,
      vice_captain_required: rules.captain.viceCaptainRequired ?? true,
      captain_points_multiplier: rules.captain.captainPointsMultiplier,
      auto_assignment: rules.captain.autoAssignment || null,
      vice_captain_rules: rules.captain.viceCaptainRules || null,
      change_rules: rules.captain.changeRules || null,
      lock_rules: rules.captain.lockRules || null
    },
    substitutions: {
      rules_status: rules.substitutions.rulesStatus,
      details: rules.substitutions.details || [],
      manual_substitution_rules: rules.substitutions.manualSubstitutionRules || null,
      lock_rules: rules.substitutions.lockRules || null
    },
    transfers: {
      rules_status: rules.transfers.rulesStatus,
      details: rules.transfers.details || [],
      free_transfers: rules.transfers.freeTransfers || {}
    },
    boosters: {
      rules_status: rules.boosters.rulesStatus,
      details: (rules.boosters.details || []).map((booster) => ({
        booster_id: booster.boosterId,
        label: booster.label,
        effect: booster.effect || null,
        constraints: booster.constraints || null,
        availability: booster.availability || null,
        activation_restrictions: booster.activation_restrictions || null,
        effect_summary: booster.effect_summary || null,
        source_url: booster.source_url || null,
        source_checked: booster.source_checked || null,
        data_quality_flags: booster.data_quality_flags || []
      }))
    },
    scoring: {
      rules_status: rules.scoring.rulesStatus,
      categories: (rules.scoring.categories || []).map((category) => ({
        category_id: category.categoryId,
        label: category.label,
        points: category.points ?? null,
        points_by_position: category.pointsByPosition || null,
        applies_to: category.appliesTo || null,
        detail: category.detail || null
      }))
    },
    deadlines: {
      rules_status: rules.deadlines.rulesStatus,
      matchdays: rules.deadlines.matchdays || [],
      deadline_rules: rules.deadlines.deadlineRules || null,
      lock_windows: rules.deadlines.lockWindows || null,
      manual_check_required: true
    },
    validation_checks: {
      check_squad_size: true,
      check_position_counts: true,
      check_budget: true,
      check_country_limit: true,
      check_starting_11: true,
      check_captain: true,
      manual_check_deadlines: true,
      manual_check_live_locks: true,
      manual_check_boosters: true
    }
  };
}

const imported = JSON.parse(await readFile(INPUT, "utf8"));
const officialRules = imported.officialFantasyRules;
const activeRules = snakeRules(officialRules);

await writeFile(ROOT_RULES, `${JSON.stringify(activeRules, null, 2)}\n`, "utf8");
await writeFile(DATA_RULES, `${JSON.stringify(activeRules, null, 2)}\n`, "utf8");
await writeFile(
  BROWSER_RULES,
  [
    "// Browser-ready copy of fantasyRules.json.",
    "// Generated by scripts/promoteOfficialFantasyRules.mjs from data/officialFantasyRules_v0.json.",
    `window.FANTASY_RULES_DATA = ${JSON.stringify(activeRules, null, 2)};`,
    ""
  ].join("\n"),
  "utf8"
);

console.log(`Promoted official fantasy rules to ${ROOT_RULES}, ${DATA_RULES}, and ${BROWSER_RULES}.`);
